version: "3.7"
services:
    # image project
    laravel_8:
        build: 
            args: 
                user: ebenezer
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - laravel-eti
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-eti

    # db mysql
    mysql:
        image: mysql:latest
        restart: unless-stopped
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3306:3306
        networks: 
            - laravel-eti

    # queue
    queue:
        build: 
            args: 
                user: ebenezer
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        networks: 
            - laravel-eti

networks: 
    laravel-eti:
        driver: bridge